import type { Offer } from '@/types';

// Offers are ranked per persona by the decision engine, so the Offers surface
// re-orders when you switch shopper. All values illustrative.

export const offers: Offer[] = [
  {
    id: 'themari-2x-dairy',
    kind: 'themari',
    title: '2× Themari points on Dairy',
    subtitle: 'All week on Almarai, Nadec & Puck',
    valueLabel: 'Earn 2× points',
    emoji: '🥛',
    imageId: 'milk-nadec',
    category: 'dairy',
    tags: ['staple'],
    baseScore: 70,
    themariLinked: true,
    disclaimer: 'Illustrative. Subject to Themari programme rules.',
  },
  {
    id: 'back-to-school-lunchbox',
    kind: 'personal',
    title: 'Back-to-school lunchbox picks',
    subtitle: 'Save on snacks, juice & bread',
    valueLabel: 'Up to 20% off',
    emoji: '🎒',
    imageId: 'milk-bread',
    tags: ['back-to-school', 'kids'],
    baseScore: 64,
    themariLinked: false,
  },
  {
    id: 'family-packs',
    kind: 'category',
    title: 'Family packs, bigger savings',
    subtitle: 'Poultry, rice & water multipacks',
    valueLabel: 'Save more per unit',
    emoji: '👨‍👩‍👧‍👦',
    imageId: 'chicken-whole',
    category: 'poultry',
    tags: ['family-pack', 'value'],
    baseScore: 66,
    themariLinked: false,
  },
  {
    id: 'organic-produce',
    kind: 'category',
    title: 'Organic produce − 15%',
    subtitle: 'Fresh, leafy & seasonal',
    valueLabel: '15% off',
    emoji: '🥬',
    imageId: 'baby-spinach',
    category: 'fruits-veg',
    tags: ['organic', 'healthy'],
    baseScore: 55,
    themariLinked: false,
  },
  {
    id: 'weekend-hosting',
    kind: 'category',
    title: 'Weekend hosting deals',
    subtitle: 'Premium cuts & seafood',
    valueLabel: 'Chef-grade savings',
    emoji: '🍽️',
    imageId: 'salmon-fillet',
    category: 'meat',
    tags: ['entertaining', 'premium'],
    baseScore: 58,
    themariLinked: false,
  },
  {
    id: 'basmati-5kg',
    kind: 'basket',
    title: 'Save on Al Safi Basmati 5KG',
    subtitle: 'Stock up the pantry',
    valueLabel: 'SAR 7 off',
    emoji: '🍚',
    imageId: 'basmati-rice',
    category: 'pantry',
    brand: 'Al Safi',
    tags: ['value', 'family-pack'],
    baseScore: 62,
    themariLinked: false,
  },
  {
    id: 'themari-3x-fresh',
    kind: 'themari',
    title: '3× Themari points on Fresh produce',
    subtitle: 'Fruits & vegetables all week',
    valueLabel: 'Earn 3× points',
    emoji: '🍎',
    imageId: 'strawberry',
    category: 'fruits-veg',
    tags: ['fresh', 'healthy'],
    baseScore: 60,
    themariLinked: true,
    disclaimer: 'Illustrative. Subject to Themari programme rules.',
  },
  {
    id: 'premium-meat',
    kind: 'category',
    title: 'Premium cuts for less',
    subtitle: 'Ribeye, lamb chops & more',
    valueLabel: 'Up to 15% off',
    emoji: '🥩',
    imageId: 'lamb-chops',
    category: 'meat',
    tags: ['premium', 'entertaining'],
    baseScore: 53,
    themariLinked: false,
  },
  {
    id: 'water-multipack',
    kind: 'basket',
    title: 'Berain Water 40-pack deal',
    subtitle: 'Everyday essential',
    valueLabel: 'SAR 2 off',
    emoji: '💧',
    imageId: 'water-berain',
    category: 'beverages',
    tags: ['value', 'family-pack'],
    baseScore: 68,
    themariLinked: false,
  },
  {
    id: 'breakfast-bundle',
    kind: 'personal',
    title: 'Breakfast bundle',
    subtitle: 'Milk, eggs, cereal & juice',
    valueLabel: 'Bundle & save',
    emoji: '🥣',
    imageId: 'cornflakes',
    tags: ['kids', 'staple', 'back-to-school'],
    baseScore: 57,
    themariLinked: false,
  },
];
